### ISSUE TITLE
Pipenv v10.0.0 support

### ISSUE THREAD

**Issue by pwalsh** [pwalsh/pipenv.el#18]
# Description

v10.0.0 is out, and has some improved commands.

# Tasks

- [ ] Support new commands (e.g.: `pipenv sync`)
- [ ] Leverage improved responses (e.g.: `pipenv --version`)
- [ ] Add basic handling to support Pipenv version changes going forward (v.10.0.0 forward)
- [ ] Expand the high-level interface, e.g.: pipenv-packages, pipenv-locked-packages, pipenv-dev-packages ([ref.](https://github.com/kennethreitz/pipenvlib#example-usage))

**Comment by pwalsh** [comment]
https://github.com/pypa/pipenv/blob/master/HISTORY.txt

Now up to v11 :)

**Comment by pwalsh** [comment]
https://github.com/pwalsh/pipenv.el/issues/45
